/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.ScrollEvent;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) {
    }

    public static void main(String[] args) {
        //launch(args);
        System.exit(0);
    }
}

